name: trucvb_workspace
publish_to: 'none'
description: 'Root workspace for trucvb app monorepo'

environment:
  sdk: '>=3.5.4 <4.0.0'

workspace:
  - app
  - shared
  - domain
  - data
  - initializer
  - resources
  - nals_lints

dev_dependencies:
  melos: ^6.2.0
